sudo: required
dist: trusty
language: python
python:
  - 3.6
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

  - pip install -q Flask==0.12
  - pip install -q -r dev_requirements.txt
  - nvm install node
  - cd test_site/web && npm install && cd ../..

script:
  - python run-test-site-travis.py &
  - cd test_site/web
  - (npm start > /dev/null &) && (npm run protractor)
  - cd ../..
